# Generated by Django 5.2.3 on 2025-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_size_choice',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('ENTERPRISE', 'Enterprise')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_size_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
